name: build-and-push

on:
  push:
    branches:
      - 'master'
      - 'test'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ronlut/pusher-fake
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
